platform :ios, '9.0'

#屏蔽三方框架警告
inhibit_all_warnings!

target 'ProjectSwiftDemo' do

  use_frameworks!

    pod 'SnapKit'
    pod 'Alamofire'
    pod 'Cache'
    pod 'Toast-Swift'
    pod 'CocoaChainKit'
    pod 'EachNavigationBar'
    pod 'MJRefresh'
    pod 'Kingfisher'
    pod 'XLPagerTabStrip'
    
    pod 'CocoaDebug'
    pod 'Bugly'

end
